tests:
    hello:
        assertStdoutEqual: "Hello World"
        input:
            - "Hello World"
software:
    python:
        execute: ["node", "-e", "console.log('[[tests]]');"]
        install:
            - ./configure
            - make -j4
            - make install
            - find ./
